package:
    type:           yii2-extension
    name:           hipanel-core
    namespace:      hipanel
    headline:       HiPanel Core
    title:          HiPanel core package
    homepage:       https://hipanel.com/
    keywords:       hipanel, control panel, hosting, domains
    description: |
        [![Logo](https://raw.githubusercontent.com/hiqdev/hipanel-core/master/docs/logo.png)](https://hipanel.com/)

        [HiPanel](http://hipanel.com) is next generation control panel for hosting, domains and more.
        This package is the core of the system.

require:
    hiqdev/hidev-php:    "*"
    hiqdev/hidev-vendor: "*"

