package:
    name:           hipanel-core
    namespace:      hipanel
    label:          HiPanel
    title:          HiPanel - Next Generation Control Panel
    type:           yii2-extension
    homepage:       https://hipanel.com/
    keywords:       hipanel, control panel, hosting, domains
    year:           2014
    description: |
        Goals:
        - Integration
        - Extensibility
        - Friendliness
        - Reliability
        - Security

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"

