package:
    name:           hipanel-core
    namespace:      hipanel
    label:          HiPanel
    title:          HiPanel - Next Generation Control Panel
    type:           project
    homepage:       https://hipanel.com/
    keywords:       hipanel, control panel, hosting, domains
    description: |
        Goals:
        - Integration
        - Extensibility
        - Friendliness
        - Reliability
        - Security
    year:           2014

require:
    hiqdev/hidev-config-php:    "*@dev"

